### PR TITLE
ST-378: java build fixes. 8->7, proper version, style fixes

### PR DESCRIPTION
**Pull request by norwood**

### CODE REVIEW

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
retest this please

**Comment by norwood** [comment]
this pr allows us to build on jenkins. and even better, tests now pass

**Comment by norwood** [comment]
i updated it to use `${CP_VERSION}`: https://github.com/confluentinc/cp-docker-images/pull/257/files#diff-b67911656ef5d18c4ae36cb6741b7965R33

i just manually ran the formatter in intellij for all the files. once this gets in i can merge down to master and have master use the common style configs 😎

**Comment by rancp** [comment]
lgtm

**Pull request merged**
