### PR TITLE
Ensure ssl.client.auth is set as required for clustered ssl configs

### PR DESCRIPTION
**Pull request by lostick**
Fix for `SSL handshake failed` exception thrown in 4.1.0 (see [#468](https://github.com/confluentinc/cp-docker-images/issues/468))
Tested on our clusters and it works fine.

### CODE REVIEW

**Comment by lostick** [comment]
[clabot:check]

**Comment by gAmUssA** [comment]
@lostick could you rebase this PR master?

**Comment by lostick** [comment]
@gAmUssA done 👍

**Comment by ijuma** [comment]
Do we understand why this worked in 4.0.0 without this change?

**Pull request closed without merging**
