### PR TITLE
replaced KAFKA_DATA_DIRS by KAFKA_LOG_DIRS to bug in ensure

### LINKED ISSUE #183: Confusion between KAFKA_LOG_DIRS and KAFKA_DATA_DIRS ??
Hi,

I'm looking at the bootstrap scripts and it seems that their might be some confusion between two environment variables? The scenario is the following, if I want to set a custom `KAFKA_LOG_DIRS`, I set that variable to `/mnt/kafka-logs`. This is fine and gets picked up here: https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka/include/etc/confluent/docker/configure#L36

And then the "ensure" script runs, and checks for `KAFKA_DATA_DIRS` at https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka/include/etc/confluent/docker/ensure#L22 

Shouldn't this variable be also `KAFKA_LOG_DIRS` for consistency and actually doing the right check? I'm happy to provide a PR if that's indeed a bug. 

Cheers,
Stephane

### PR DESCRIPTION
**Pull request by simplesteph**
this fixes #183

### CODE REVIEW

**Comment by simplesteph** [comment]
just signed it

**Comment by arrawatia** [comment]
@simplesteph Thanks for the PR.

**Comment by ankon** [comment]
Somehow this commit seems to have gotten lost recently: https://github.com/confluentinc/cp-docker-images/commits/v4.0.0/debian/kafka/include/etc/confluent/docker ... cloning locally and checking out that tag however does show these:
~~~~
1111593 Tue, 31 Jan 2017 14:19:56 -0800 fixed typo (#215) [Sam Hecht]
22c88ff Tue, 13 Dec 2016 09:57:10 -0800 replaced KAFKA_DATA_DIRS by KAFKA_LOG_DIRS to bug in ensure (#184) [Sumit Arrawatia]
9048a40 Fri, 21 Oct 2016 07:17:30 +0530 Use env_to_props for kafka properties (#150) [GitHub]
~~~~
On an actual docker image I still see the original `KAFKA_DATA_DIRS` reference.

I'm quite confused now what is happening here, especially since the hashes seem to match.

**Comment by jimymodi** [comment]
@ankon Same happened with me. Curious to know what and how happened here.

**Pull request merged**
