### PR TITLE
Add zookeeper-connect in docker-compose example for rest proxy

### PR DESCRIPTION
**Pull request by stanislavkozlovski**

### CODE REVIEW

**Comment by gAmUssA** [comment]
@stanislavkozlovski out of curiosity, why bother with zookeeper connect?

**Comment by stanislavkozlovski** [comment]
@gAmUssA 

the REST proxy has always needed a zookeeper connection for the v1 consumers. I tested the v1 api and saw that it didn't work because it tried to connect to the default `localhost:2181`
I imagine that this example has never worked with the v1 API consumers.

**Comment by gwenshap** [comment]
@stanislavkozlovski should we merge or close?

**Comment by andrewegel** [comment]
Next time please pint-merge these changes up.

**Pull request merged**
