### PR TITLE
Bump to 5.1.0-snapshot

### PR DESCRIPTION
**Pull request by mohnishbasha**
Bump to 5.1.0-snapshot, since trunk points to 5.1.0 (5.1.x)
- Bumped CF and AK in Makefile.
- Bumped parent.version in java/pom.xml

### CODE REVIEW

**Review by aayars — CHANGES_REQUESTED** [review]
Can you update the version in Makefile too?

**Comment by mohnishbasha** [comment]
@aayars Max already pushed this:
https://github.com/confluentinc/cp-docker-images/pull/506#issuecomment-396678084

**Comment by maxzheng** [comment]
@mohnishbasha mine was just for 5.0.x branch. You still need to make the change here for 5.1.0.

**Review by maxzheng — APPROVED** [review]
Thanks for fixing this!

**Comment by mohnishbasha** [comment]
No worries, needed this to validate changes i made in cp-docker-images-overlay to support beta and rc.

**Pull request merged**
