### PR TITLE
Add second listener and some text explaining its use

### PR DESCRIPTION
**Pull request by rmoff**
We need an example that shows people how to wire Kafka on Docker for both internal and external connections.

### CODE REVIEW

**Comment by ybyzek** [comment]
@rmoff : the enhancement to the `KAFKA_ADVERTISED_LISTENERS` parameter is great. With regard to the added comment, please consider (a) augmenting docs.confluent.io with this information and (b) removing the comment from the docker-compose file and instead adding a link to the docs?

**Comment by rmoff** [comment]
@ybyzek (a) sure, I can suggest adding this (b) why remove it? It's not going to go out of date as such, and makes it more accessible for devs (and more likely they'll read it)

**Comment by ybyzek** [comment]
My thinking is that if anything changes, you need to chase it down in duplicate places.  This is how things fall out of date.

In terms of getting devs to read it, would a link to docs from docker-compose file not get them there?

Or.... add a README?

**Comment by rmoff** [comment]
I'm going to merge this in as-is, and track the docs improvement separately. Once made, I'll replace the comment with the docs URL.

**Comment by rmoff** [comment]
Internal issue id DOCS-822

**Pull request merged**
