### PR TITLE
Feature/rest proxy cors headers

### PR DESCRIPTION
**Pull request by fhalim**
Copy the CORS related headers for the REST Proxy into the generated config file so that they get picked up by the CrossOriginFilter.

### CODE REVIEW

**Comment by samjhecht** [comment]
Hi @fhalim - can you please sign our CLA? http://clabot.confluent.io/cla

Once that's done, I'll get this merged.

**Comment by fhalim** [comment]
Signed CLA.

**Comment by samjhecht** [comment]
Thanks.  Merging.

**Comment by fhalim** [comment]
Thanks for merging. Could you kick off a build for this? Doesn't like this repo is set up for docker hub trusted builds.

**Comment by samjhecht** [comment]
Hi @fhalim - the build will happen tomorrow.  I'll let you know once the new image versions are available.

**Comment by samjhecht** [comment]
@fhalim the new images have now been uploaded to Docker Hub: https://hub.docker.com/r/confluentinc/cp-kafka-rest/

**Pull request merged**
