### PR TITLE
Adapt to KAFKA-4636 changes

### PR DESCRIPTION
**Pull request by ijuma**
I am creating this and other PRs for review before merging apache/kafka#2406.

### CODE REVIEW

**Comment by ijuma** [comment]
Review by @arrawatia.

**Comment by ijuma** [comment]
@ewencp, maybe you can review this trivial change.

**Comment by ijuma** [comment]
This change only makes sense if the repo depends on Kafka trunk whereas it currently depends on `0.10.0.0-cp1`. I included the version bump in this PR, in case that is desired, but if not, we should just close this.

**Comment by arrawatia** [comment]
Yes. We should bump it up to 0.10.2.0 (at least for the 3.1.2 branch).

**Pull request merged**
