### PR TITLE
add kafka connect plugin path to the environment variable

### PR DESCRIPTION
**Pull request by evolv34**
Hi All,

All Connect plugins are not listing from localhost:8083/connector-plugins in kafka connect docker image. Its fixed in this PR. It would be great if somebody can take a look at this PR ?

### CODE REVIEW

**Comment by perryao** [comment]
I had to do this myself. But not sure why it's necessary. FWIW, the file source and file sink are the only two that show up without this set.

**Comment by evolv34** [comment]
This doesn’t list any other connectors like HDFS connectors or elastic search connectors that available out of the box in Confluent platform. So this fix would and list these connectors as well.

**Comment by evolv34** [comment]
This fix would be helpful when developers refer to this yml file. Many developers use this as a point of reference while using containers.

**Comment by johnseekins** [comment]
Agreed with above. The documentation implies that the built in plugins will be loaded by default. This isn't the case without @evolv34 's change.

**Comment by cricket007** [comment]
Superseded by #464

**Comment by evolv34** [comment]
Can it be merged ?

**Comment by cricket007** [comment]
It was. See the other issue

**Pull request closed without merging**
