### PR TITLE
print() is a function in modern Python

### PR DESCRIPTION
**Pull request by cclauss**
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.

__xrange()__ was removed in Python 3 in favour of an iterator-base version of __range()__.  In Python 2, for low values for __n__ there is no appreciable difference __xrange(n)__ and __range(n)__.

### CODE REVIEW

**Comment by cricket007** [comment]
Are these the only issues?

You could try running 2to3 on the script

**Comment by cclauss** [comment]
2to3 is bad idea.  It often breaks Python 2 functionality to achieve Python 3 compatibility.  Use [futuzize](https://pypi.org/project/future) or [modernize](https://pypi.org/project/modernize) instead if you want to retain compatibility with Python 2.

**Comment by cclauss** [comment]
This PR is the syntax errors plus the undefined names.  I would recommend landing these change and testing functionality before adding other changes.

**Comment by cricket007** [comment]
Fair enough, I was just suggesting upgrading the whole script to py3, not exactly prescribing the solution

**Pull request closed without merging**
