### PR TITLE
Updating references for 3.1.1

### PR DESCRIPTION
**Pull request by samjhecht**
- update docs
- update references in examples
- update build number on images
- update makefile

### CODE REVIEW

**Comment by samjhecht** [comment]
@arrawatia @theduderog - I need to run the tests once the new packages are on prod, but wanna go ahead and take a look and see if I missing anything?

**Comment by arrawatia** [comment]
LGTM.

**Comment by theduderog** [comment]
i don't think we need to increment the BUILD_NUMBER

**Comment by theduderog** [comment]
LGTM

**Pull request merged**
