### PR TITLE
Remove obsolete warning about images on Mac

### PR DESCRIPTION
**Pull request by aayars**

### CODE REVIEW

**Review by maxzheng — APPROVED** [review]
As long as we have run the images on Mac and it works.

**Review by ewencp — COMMENTED** [review]
Is this safe to remove? I still can't run the quickstart under docker for mac. It still bails with errors about `moby`.

**Comment by aayars** [comment]
I've been able to work with the images without issue, but I'll go through the quickstart before committing.

**Comment by ewencp** [comment]
@aayars For reference, I'm on 
```
Docker CE
Version 17.06.0-ce-mac19 (18663)
Channel: stable
c98c1c25e0
```

**Comment by hjespers** [comment]
Need to remove the reference to docker machine in the Quickstart and also
change the version numbers to be 3.3.0 and not 3.3.0-SNAPSHOT.

I'm testing the rest now

-hans

/**
 * Hans Jespersen, Principal Systems Engineer, Confluent Inc.
 * hans@confluent.io (650)924-2670
 */

**Comment by hjespers** [comment]
Works for me if I add "--add-host=moby:127.0.0.1" to the start kafka docker
command

docker run -d \
    --net=host \
    --add-host=moby:127.0.0.1 \
    --name=kafka \
    -e KAFKA_ZOOKEEPER_CONNECT=localhost:32181 \
    -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092 \
    -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
    confluentinc/cp-kafka:3.3.0


/**
 * Hans Jespersen, Principal Systems Engineer, Confluent Inc.
 * hans@confluent.io (650)924-2670
 */

**Comment by hjespers** [comment]
Need to add "--add-host=moby:127.0.0.1" to the start schema-registry docker command as well

docker run -d \
  --net=host \
  --add-host=moby:127.0.0.1 \
  --name=schema-registry \
  -e SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:32181 \
  -e SCHEMA_REGISTRY_HOST_NAME=localhost \
  -e SCHEMA_REGISTRY_LISTENERS=http://localhost:8081 \
  confluentinc/cp-schema-registry:3.3.0

**Comment by ewencp** [comment]
@hjespers Yeah, so this was my point. Nothing is actually fixed or different, right? It's just that you can hack around the issues by adding more command line flags. But it doesn't makes sense to remove the warning until we've validated all the rest of the quickstart/tutorial stuff w/ extended commands (and validated nothing weird happens in non-Mac environments).

I previously ran into issues on Mac w/ Connect images even with the moby host additions and host networking, so I'd imagine users would be likely to encounter similar issues.

**Comment by hjespers** [comment]
REST Proxy also requires  --add-host=moby:127.0.0.1  to run properly


docker run -d \
  --net=host \
  --add-host=moby:127.0.0.1 \
  --name=kafka-rest \
  -e KAFKA_REST_ZOOKEEPER_CONNECT=localhost:32181 \
  -e KAFKA_REST_LISTENERS=http://localhost:8082 \
  -e KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8081 \
  -e KAFKA_REST_HOST_NAME=localhost \
  confluentinc/cp-kafka-rest:3.3.0

**Comment by hjespers** [comment]
I think just add a warning to add "--add-host=moby:127.0.0.1 " to all the run commands if running on a Mac would be sufficient though.

**Comment by hjespers** [comment]
connect is giving a error about 

Caused by: org.apache.kafka.common.errors.InvalidReplicationFactorException: replication factor: 3 larger than available brokers: 1

So this will be an problem on Linux as well as Mac. This means the docker quickstart won't work on any platform for connect

**Comment by hjespers** [comment]
OK connect seems to work when given the right configs but the rest of the quickstart is very docker-machine specific and need a bit of a rewrite to run the curl commands from a container or the local host OS. 

docker run -d \
  --name=kafka-connect \
  --net=host \
  --add-host=moby:127.0.0.1 \
  -e CONNECT_PRODUCER_INTERCEPTOR_CLASSES=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor \
  -e CONNECT_CONSUMER_INTERCEPTOR_CLASSES=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor \
  -e CONNECT_BOOTSTRAP_SERVERS=localhost:29092 \
  -e CONNECT_REST_PORT=28082 \
  -e CONNECT_GROUP_ID="quickstart" \
  -e CONNECT_CONFIG_STORAGE_TOPIC="quickstart-config" \
  -e CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1 \
  -e CONNECT_OFFSET_STORAGE_TOPIC="quickstart-offsets" \
  -e CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1 \
  -e CONNECT_STATUS_STORAGE_TOPIC="quickstart-status" \
  -e CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1 \
  -e CONNECT_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
  -e CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
  -e CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
  -e CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
  -e CONNECT_REST_ADVERTISED_HOST_NAME="localhost" \
  -e CONNECT_LOG4J_ROOT_LOGLEVEL=DEBUG \
  -v /tmp/quickstart/file:/tmp/quickstart \
  confluentinc/cp-kafka-connect:3.3.0

**Comment by hjespers** [comment]
I verified that connect works if you either map port 28082 to be visable with "-p 28082: 28082" or you ssh into the container and run all the connect curl commands from an inside shell.

docker run -it --net=host --rm confluentinc/cp-kafka-connect:3.3.0 bash
root@moby:/# curl localhost:28082
{"version":"0.11.0.0-cp1","commit":"6a8cf706ddc9ab6a"}root@moby:/#
root@moby:/# export CONNECT_HOST=localhost
root@moby:/# curl -X POST \
>   -H "Content-Type: application/json" \
>   --data '{"name": "quickstart-file-source", "config": {"connector.class":"org.apache.kafka.connect.file.FileStreamSourceConnector", "tasks.max":"1", "topic":"quickstart-data", "file": "/tmp/quickstart/input.txt"}}' \
>   http://$CONNECT_HOST:28082/connectors
{"name":"quickstart-file-source","config":{"connector.class":"org.apache.kafka.connect.file.FileStreamSourceConnector","tasks.max":"1","topic":"quickstart-data","file":"/tmp/quickstart/input.txt","name":"quickstart-file-source"},"tasks":[]}
root@moby:/# curl -X GET http://$CONNECT_HOST:28082/connectors/quickstart-file-source/status
{"name":"quickstart-file-source","connector":{"state":"RUNNING","worker_id":"localhost:28082"},"tasks":[{"state":"RUNNING","id":0,"worker_id":"localhost:28082"}]}
root@moby:/#

**Pull request closed without merging**
