### PR TITLE
kafka-connect-base: fix test condition for SSL

### PR DESCRIPTION
**Pull request by miguno**

### CODE REVIEW

**Comment by miguno** [comment]
Subtle difference, but the original test condition for SSL did not check for `If the string equals "SSL"` -- it matched even if `CONNECT_SECURITY_PROTOCOL` was set to some other, non-empty string such as "foobar".

**Comment by miguno** [comment]
Not sure whether any of the `tests/*` for kafka-connect-base would need updating, too.

**Comment by arrawatia** [comment]
Wow ! That is subtle indeed. Unfortunately, we have no SSL/SASL tests for connect. Kafka/ZK are the only components with full coverage.

Shellcheck agrees. @theduderog is there a way to include shellcheck and pep-8 checks into the build process ?
image

**Comment by theduderog** [comment]
@arrawatia Add shellcheck and pep8 steps to the Makefile?

**Pull request merged**
