### PR TITLE
Use correct branch for Kafka Streams Examples

### PR DESCRIPTION
**Pull request by miguno**

### CODE REVIEW

**Comment by miguno** [comment]
I created the `3.2.1-post` branch at [confluentinc/examples](https://github.com/confluentinc/examples) so that we can build the Docker images -- with the new changes in this PR -- in the correct way, without impacting users of the examples repository, whose default branch is `3.2.x` (and we can't bump that branch yet to use the not-yet-released 3.2.1 artifacts).

**Comment by miguno** [comment]
Eventually, this PR should also go into `3.2.x` I think.

**Comment by miguno** [comment]
Will you be merging this to 3.2.x eventually @aayars ?

**Comment by aayars** [comment]
Sure, I can do that.

**Pull request merged**
