### PR TITLE
added confluent interceptors for rest proxy

### LINKED ISSUE #335: Rest Proxy does not include confluent interceptors

### PR DESCRIPTION
**Pull request by simplesteph**
this fixes #335

### CODE REVIEW

**Comment by ewencp** [comment]
ok to test

**Comment by simplesteph** [comment]
unsure why this fails @ewencp

**Comment by ewencp** [comment]
Looks like some version # issues, I've let folks internally know about it.

**Comment by simplesteph** [comment]
ping @ewencp

**Comment by AndrewJSchofield** [comment]
Closing this PR which has been dormant for over 4 years. Please reopen if it's still valuable.

**Pull request closed without merging**
