### PR TITLE
Set Kafka offsets topic replication factor to 1 in Kafka streams examples

### PR DESCRIPTION
**Pull request by gchiam**
We need to set the offsets topic replication factor to 1 since we are running with a single-node cluster.

Kafka's logs before setting offsets topic replication factor to 1,
```
kafka_1                       | [2017-08-09 06:05:58,644] ERROR [KafkaApi-1] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
kafka_1                       | [2017-08-09 06:05:58,747] ERROR [KafkaApi-1] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
kafka_1                       | [2017-08-09 06:05:58,854] ERROR [KafkaApi-1] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
kafka_1                       | [2017-08-09 06:05:58,956] ERROR [KafkaApi-1] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
kafka_1                       | [2017-08-09 06:05:59,060] ERROR [KafkaApi-1] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
```

### CODE REVIEW

**Comment by gchiam** [comment]
[clabot:check]

**Comment by miguno** [comment]
Ping @bbejeck -- I thought you already changed/fixed this in a prior PR?

**Comment by aayars** [comment]
This was added in a416ff74. Not quite sure why github still shows a diff.

**Comment by bbejeck** [comment]
Not sure what happened either, merged the PR a while ago then merged to 3.4.x and master via pint 

https://github.com/confluentinc/cp-docker-images/commits/master?after=b1b963ef7516bb110d8d0257e122ca5da95597a6+34

**Comment by gchiam** [comment]
Closing this PR then. It appears the issue has been addressed. :)

**Pull request closed without merging**
