### PR TITLE
MMA-1437: Remove and replace custom admin client

### PR DESCRIPTION
**Pull request by ijuma**
This fixes a bug when dealing with older brokers.

### CODE REVIEW

**Comment by rgbenson** [comment]
Thanks for the quick work @ijuma !  Is it safe to assume this will be a clean merge up to master and the 3.4.x branch (at least as long as it exists)?

**Comment by ijuma** [comment]
@rgbenson yes, it should be. We should also validate that this fixed the C3 issue, I haven't yet.

**Comment by rgbenson** [comment]
@ijuma +1 We (C3 eng team) will do the validation.

**Comment by ijuma** [comment]
The PR failure is because the Kafka SNAPSHOT JAR cannot be found in Nexus:

```text
13:55:13 [ERROR] Failed to execute goal on project docker-utils: Could not resolve dependencies for project io.confluent:docker-utils:jar:3.3.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:kafka-clients:jar:0.11.0.1-SNAPSHOT, org.apache.kafka:kafka_2.11:jar:test:0.11.0.1-SNAPSHOT, org.apache.kafka:kafka_2.11:jar:0.11.0.1-SNAPSHOT, org.apache.kafka:kafka-clients:jar:test:0.11.0.1-SNAPSHOT: Could not find artifact org.apache.kafka:kafka-clients:jar:0.11.0.1-SNAPSHOT in confluent (http://packages.confluent.io/maven/) -> [Help 1]
```

**Comment by ijuma** [comment]
Synced with @aayars and the PR failure is expected. `mvn test` passes locally. I'll merge this since it's an improvement to use the supported AdminClient, but let's leave the JIRA open until the C3 team has verified that it fixes that issue. If not, we'll have to investigate more.

**Pull request merged**
