### PR TITLE
Improve security protocol handling in ensure script

### PR DESCRIPTION
**Pull request by thiagonache**
Changes if condition to != of PLAINTEXT to cover SSL and SASL_SSL. In theory, anything different of PLAINTEXT should use this configuration

### CODE REVIEW

**Comment by mageshn** [comment]
@thiagonache can you also apply the same fix in kafka-rest

**Comment by thiagonache** [comment]
done

**Comment by wicknicks** [comment]
Thanks, @thiagonache. This LGTM. Once you have @mageshn's approval, we can go ahead and merge the changes.

**Comment by wicknicks** [comment]
Actually, did you intend to push this to master, or do you want to push it to an earlier release?

**Comment by thiagonache** [comment]
I’ve built my own image for now. I can wait your release process and use
the next 4.x.x when ready. I do not need it now. Thanks for asking .

**Comment by mageshn** [comment]
LGTM

**Comment by oussemabhouri** [comment]
@thiagonache with that being changed, I guess when the broker endpoint is TLS instead of plaintext, it should pass the ensure text shouldn't it? in my case, it is still failing with TLS endpoints

**Comment by thiagonache** [comment]
hi, @oussemabhouri I'm sad you're facing this issue. Unfortunately, I have no bandwidth to work on it now. Feel free to ping any maintainer or add your own PR.

**Pull request merged**
