### PR TITLE
Use default publish.ms in metrics reporter

### PR DESCRIPTION
**Pull request by xvrl**
This creates unncessary load in C3 and is a source of many troubles.

### CODE REVIEW

**Comment by blueedgenick** [comment]
holy cow. can we see how that got in there in the first place ?

**Comment by theduderog** [comment]
@blueedgenick  that was me :)

**Comment by theduderog** [comment]
BTW, what's a reasonable value?

**Comment by xvrl** [comment]
@theduderog the default (15s) is plenty enough, otherwise we're hammering the metrics aggregation topology when there are lots of metrics (e.g. when you have hundreds of topics)

**Comment by xvrl** [comment]
@ijuma good point, I don't know @theduderog @arrawatia any ideas?

**Comment by theduderog** [comment]
no idea

**Comment by arrawatia** [comment]
I don't recall either. :)

**Pull request merged**
