### PR TITLE
Fix issue https://github.com/confluentinc/cp-docker-images/issues/176

### PR DESCRIPTION
**Pull request by sophieqianCA**
Fix Issue 176

https://github.com/confluentinc/cp-docker-images/issues/176

@arrawatia : Please review, thanks

### CODE REVIEW

**Comment by arrawatia** [comment]
LGTM.

@sophieqianCA Thanks for the PR. We can merge it once the CLA is signed.

**Comment by sophieqianCA** [comment]
@arrawatia How do I sign the CLA? I can read the agreement, but could not find any signing button. Thanks.

**Comment by samjhecht** [comment]
Hi @sophieqianCA  - you should be able to sign it here: http://clabot.confluent.io/cla

**Comment by sophieqianCA** [comment]
@samjhecht Thank you for the link, just submit the agreement.

**Comment by samjhecht** [comment]
@sophieqianCA - great!  thanks for signing it and for contributing!  Merging this now.

**Pull request merged**
