### PR TITLE
Remove mandatory internal converters configuration (deprecated AK2.0)

### LINKED ISSUE #229: cp-kafka-connect - Make internal converter env vars optional
`CONNECT_INTERNAL_KEY_CONVERTER` and `CONNECT_INTERNAL_VALUE_CONVERTER` environment variables need to be set when using the docker image. [link](https://github.com/confluentinc/cp-docker-images/blob/3.2.0-post/debian/kafka-connect-base/include/etc/confluent/docker/configure#L29-L30)
However considering that these should never be changed from the [default `JsonConverter` class](https://github.com/apache/kafka/blob/trunk/config/connect-distributed.properties#L35), I propose that these environment variables be defaulted to JsonConverter class and be optional. [discussion](https://confluentcommunity.slack.com/archives/connect/p1488991284001084)

### PR DESCRIPTION
**Pull request by rmoff**
Fixed #229

### CODE REVIEW

**Comment by ybyzek** [comment]
@rmoff are all the following also target for removal?

```bash
cp-all-in-one/docker-compose.yml:      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
cp-all-in-one/docker-compose.yml:      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
cp-all-in-one-cloud/docker-compose.yml:      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
cp-all-in-one-cloud/docker-compose.yml:      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
enterprise-replicator/docker-compose.yml:      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
enterprise-replicator/docker-compose.yml:      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
enterprise-replicator/docker-compose.yml:      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
enterprise-replicator/docker-compose.yml:      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
multi-datacenter/docker-compose.yml:      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
multi-datacenter/docker-compose.yml:      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
multi-datacenter/docker-compose.yml:      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
multi-datacenter/docker-compose.yml:      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
```

**Comment by rmoff** [comment]
> @rmoff are all the following also target for removal?
> 
> ```shell
> cp-all-in-one/docker-compose.yml:      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
>[…]
> ```

Yes they could be, but I'm keeping this PR deliberately small just to target the root file which mandates the presence of the config. 
Once merged we can follow up and remove the config from these Docker Composes but their presence will simply be superfluous than break anything.

**Comment by ybyzek** [comment]
> Once merged we can follow up and remove the config from these Docker Composes but their presence will simply be superfluous than break anything.

It would be simpler and less confusing to remove it in one PR

**Comment by rmoff** [comment]
> It would be simpler and less confusing to remove it in one PR

Done.

**Comment by rmoff** [comment]
> @rmoff these configs were deprecated with AK 2.0/CP 5.0. Should we alter the PR to target 5.0.x?

Good point. Redone as #761

**Pull request closed without merging**
